name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with Java 21
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
      - name: Build with Gradle
        run: ./gradlew build --stacktrace