name: Build

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with Java 21
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Prepare workspace
        run: ./gradlew prepareWorkspace --stacktrace
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
