name: Publish

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with Java 21
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Install DataConverter
        run: ./installDataConverter.sh
      - name: Prepare workspace
        run: ./gradlew prepareWorkspace --stacktrace
      - name: Build with Gradle
        run: ./gradlew fatBootJar --stacktrace
      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +%s) >> $GITHUB_OUTPUT"
      - name: Publish Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/papermc/item-converter:latest
            ghcr.io/papermc/item-converter:${{ steps.timestamp.outputs.timestamp }}
